### ISSUE TITLE
[libmspack Patch] MinGW: "error: too many arguments to function 'mkdir'"

### ISSUE THREAD

**Issue by AntumDeluge** [kyz/libmspack#1]
There is an error in the file _test/chmx.c_ of _libmspack_ when building on Win32 with MinGW:

> error: too many arguments to function 'mkdir'

On Win32 the _mkdir_ command only uses a single argument. It does not support the permissions flags of Unix systems.

Attached is a patch to fix this. It checks for definitions of "__WIN32__" or "__MINGW32__" and changes the _mkdir_ command from _mkdir(path, flags)_ to _mkdir(path)_.

[libmspack-0.5-cef3a03_test__chmx.c.patch.txt](https://github.com/kyz/libmspack/files/51229/libmspack-0.5-cef3a03_test__chmx.c.patch.txt)

**Comment by kyz** [comment]
Thanks for the patch. Would [this ax_func_mkdir patch](https://github.com/kyz/libmspack/commit/6f359d12e1f0f56a0dcb3f1e2074c51f663cfec2), in cabextract, but not libmspack, also solve the problem? If so, I could just bring it across to libmspack.

**Comment by AntumDeluge** [comment]
Yes, that works. I had no problems compiling *cabextract*. I recently compiled from *git* commit number *cef3a03*, which apparently already has that patch added.

**Comment by AntumDeluge** [comment]
So it would probably be best to use the *MKDIR_TAKES_ONE_ARG* macro instead of the ones that I used (*__WIN32__ || __MINGW32__*) in *libmspack* so it matches *cabextract*. I think the way that you did it is better anyway.

**Comment by kyz** [comment]
Thanks for the patch. libmspack now checks for one-arg mkdir() in the configure script and supports it in src/chmextract.c

**Comment by wA1WA1234** [comment]
> Thanks for the patch. libmspack now checks for one-arg mkdir() in the configure script and supports it in src/chmextract.c

Are you guys still there... How do you add this patch for mkdir in dev++

**Comment by kyz** [comment]
I don't know what dev++ is (some kind of MS-DOS compiler?) but this patch was applied in 2017. Just be sure to have this in your config.h
```
#define HAVE_MKDIR 1
#define MKDIR_TAKES_ONE_ARG 1
```
