### ISSUE TITLE
[libmspack Patch] autogen.sh

### ISSUE THREAD

**Issue by AntumDeluge** [kyz/libmspack#2]
Attached is a patch to add an _autogen.sh_ script if you would like to add it to libmspack.
[libmspack-0.5-cef3a03_autogen.sh.patch.txt](https://github.com/kyz/libmspack/files/51233/libmspack-0.5-cef3a03_autogen.sh.patch.txt)

**Comment by AntumDeluge** [comment]
I messed up on that autogen patch. I'm pretty sure that *aclocal* should be run before *libtoolize*.

**Comment by kyz** [comment]
Thanks for your patch. I'd like to check -- does this do something different from what rebuild.sh does today?

rebuild.sh runs `cleanup.sh`, then `autoreconf`, then performs a configure, make, etc.

`autoreconf` runs `aclocal`, `libtoolize`, `autoconf`, `autoheader` and `automake`. Example:

    $ ./cleanup.sh
    $ mkdir m4
    $ autoreconf -vfi
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -I m4
    autoreconf: configure.ac: tracing
    autoreconf: running: libtoolize --copy --force
    libtoolize: putting auxiliary files in `.'.
    libtoolize: copying file `./ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: copying file `m4/ltoptions.m4'
    libtoolize: copying file `m4/ltsugar.m4'
    libtoolize: copying file `m4/ltversion.m4'
    libtoolize: copying file `m4/lt~obsolete.m4'
    autoreconf: running: /usr/bin/autoconf --force
    autoreconf: running: /usr/bin/autoheader --force
    autoreconf: running: automake --add-missing --copy --force-missing
    configure.ac:27: installing './ar-lib'
    configure.ac:25: installing './compile'
    configure.ac:29: installing './config.guess'
    configure.ac:29: installing './config.sub'
    configure.ac:6: installing './install-sh'
    configure.ac:6: installing './missing'
    Makefile.am: installing './INSTALL'
    Makefile.am: installing './depcomp'
    autoreconf: Leaving directory `.'

**Comment by AntumDeluge** [comment]
No, I guess it doesn't do anything more. I didn't realize that *rebuild.sh* runs *autoreconf*. I don't like to have the script run *configure* and *make* though. After I run autotools, I usually like to setup my build in a different directory, then run *configure* and *make* from there.

**Comment by kyz** [comment]
Thanks for the feedback. I've changed the build scripts slightly.

* cleanup.sh will delete all auto-generated / compiled files
* autogen.sh will recreate the autotools files (using autoreconf), it will not run cleanup.sh, configure or make
* rebuild.sh will run cleanup.sh, autogen.sh, configure, make
