### ISSUE TITLE
where is configre file?

### ISSUE THREAD

**Issue by TAVVANNA** [kyz/libmspack#4]
I can't find it !!!

**Comment by kyz** [comment]
As [the documentation says](http://www.cabextract.org.uk/libmspack/):

* the [downloadable](http://www.cabextract.org.uk/libmspack/libmspack-0.5alpha.tar.gz) release of libmspack can be built in a UNIX or UNIX-like environment with `./configure && make`
* If obtaining libmspack from the Git repository, use the `rebuild.sh` script instead (this requires at least autoconf 2.57, automake 1.7 and libtool)"
