### ISSUE TITLE
please push forward expand.c

### ISSUE THREAD

**Issue by stsp** [kyz/libmspack#5]
Hello.

Currently expand.c resides in a "test" directory,
which makes it being skipped by the distributions.
Unfortunately, there seem to be no other extractor
for the mscompress files.
Can expand.c be moved to the more visible location,
where it will be picked up by the distributions?
Maybe it should even became a part of cabextract?

**Comment by kyz** [comment]
expand.c is now src/msexpand.c and installs automatically as the "msexpand" command
