### ISSUE TITLE
Decompressing files in memory?

### ISSUE THREAD

**Issue by samsonsite1** [kyz/libmspack#6]
Please add support for decompressing files that have already been loaded into memory.

I'm trying to use mszipd_init() and mszipd_decompress(), but it will only work with file handles.

Or if it already does it, then I would like to see a C/C++ coding example of how to decompress a file loaded in a memory buffer.  Thanks.

**Comment by samsonsite1** [comment]
Ah, nevermind.  I figured it out.  I had to create my own file system, and remove the default file system, mspack_default_system.

But, it would have been much easier if libmspack had an C/C++ coding example of a file system that reads/writes from memory, instead of using file handles, so people could just use that as a starting point.  So, stil requesting a coding example for the docs.

**Comment by kyz** [comment]
Hi samsonite1, the libmspack README has an example code section mentioning two relevant example programs:

* [cabd_memory](https://github.com/kyz/libmspack/blob/master/libmspack/test/cabd_memory.c) - An mspack_system implementation that reads/writes to memory.
* [multifh](https://github.com/kyz/libmspack/blob/master/libmspack/test/multifh.c) - An mspack_system implementation that can simultaneously work on in-memory images, raw file descriptors, open file handles and regular disk files.

**Comment by kyz** [comment]
I've created a new directory, `examples/`, which contains the cabd_memory.c and multifh.c programs. This should make them more findable
